### ISSUE TITLE
can you lazy load npm modules

### ISSUE THREAD

**Issue by PTAHume** [JLarky/react-lazily#2]
this is fantastic when using your own components,  but if I wanted to lazy load a npm package component it doesn't seem to be able to lazy load that in.

for example, I have the [react-tooltip](https://www.npmjs.com/package/react-tooltip) npm package component that's added based on a condition

```
{activity.host?.following && (
    <Tooltip id="following" place='left' />
)}
```

so I'd like to lazy load it in, normally it would be

```
import { Tooltip } from 'react-tooltip';
```

however, if I use lazily load instead
```
const { Tooltip } = lazily(() => import("react-tooltip"))
```

The component doesn't show, but VSCode shows that it knows the component location in the npm packages, so not sure why this wouldn't work ?

dose or can this package support lazily loading other npm packages?

**Comment by JLarky** [comment]
Hi! So to be honest I never used it with npm packages before but there's nothing that should prevent you form using it :)

I tried this code and it worked

```ts
"use client";

import { Suspense } from "react";
import { lazily } from "react-lazily";

const { Tooltip } = lazily(() => import("react-tooltip"));

export default function Home() {
  return (
    <Suspense fallback={null}>
      <div data-tooltip-id="following" data-tooltip-content="Hello world!">
        hover me
      </div>
      <Tooltip id="following" place="bottom" />
    </Suspense>
  );
}
```

I did it on a clean nextjs install:
```bash
bunx create-next-app
cd my-app/
bun add react-tooltip react-lazily
code src/app/page.tsx
bun dev
```

**Comment by PTAHume** [comment]
Yes, sorry I was mistaken, it actually worked from the beginning but the browser cache was able to fool me into thinking it didn't despite the fact I was sure I had cleared it out beforehand 🤪
